version: 0.2
phases:
  install:
    runtime-versions:
      dotnet: 6.0
  pre_build:
    commands:
      - dotnet restore QuizBackend.csproj
  build:
    commands:
      - dotnet build QuizBackend.csproj
  post_build:
    commands:
      - dotnet publish -c Release -o ./app/ QuizBackend.csproj
artifacts:
  files:
    - '**/*'
    - '.ebextensions/**/*'
    - '.platform/**/*'